services:
  mongodb:
    image: mongo:latest
    container_name: million_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - million-network
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: million.api/Dockerfile
    container_name: million_api
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - MongoDbSettings__ConnectionString=mongodb://admin:password@mongodb:27017/
      - MongoDbSettings__DatabaseName=million
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - million-network
    restart: unless-stopped

networks:
  million-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
